---
resources:
  - name: resume-git
    type: git
    source:
      uri: https://github.com:xetamus/resume.git
      branch: master

  - name: resume-app
    type: cf
      source:
        api: https://api.run.pivotal.io
        username: ((cf_username))
        password: ((cf_password))
        organization: ((cf_org))
        space: ((cf_space))

jobs:
  - name: push-resume
    plan:
      - get: resume-git
      - task: build-resume
        file: resume-git/ci/tasks/build-resume/task.yml
      - task: generate-app-manifest
        file: resume-git/ci/tasks/generate-app-manifest/task.yml
        params:
          APP_NAME: ((app_name))
          APP_ROUTE: ((app_route))
          APP_MEMORY: ((app_memory))
          APP_INSTANCES: ((app_instances))
      - put:  resume-app
        params:
          manifest: app-manifest/manifest.yml
