---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: xetamus/docker-hackmyresume

inputs:
  - name: resume-git
outputs:
  - name: resume

run:
  path: hackmyresume
  args:
    - BUILD
    - resume-git/resume.json
    - TO
    - resume/index.html
    #- -t
    #- resume-git/jsonresume-theme-xetamus
